package pt.isel

import org.cojen.maker.ClassMaker
import org.cojen.maker.MethodMaker
import org.cojen.maker.Variable
import pt.isel.interfaces.YamlParser
import java.lang.reflect.Modifier
import java.lang.reflect.Parameter
import java.lang.reflect.Type
import kotlin.reflect.KClass
import kotlin.reflect.cast
import kotlin.reflect.javaType

/**
 * A YamlParser that uses Cojen Maker to generate a parser.
 */
open class YamlParserCojen<T : Any>(
    private val type: KClass<T>,
    private val nrOfInitArgs: Int)
: AbstractYamlParser<T>(type) {

    companion object {
        private val yamlParsers: MutableMap<String, YamlParserCojen<*>> = mutableMapOf()

        private fun parserName(type: KClass<*>, nrOfInitArgs: Int): String {
            return "YamlParser${type.simpleName}$nrOfInitArgs"
        }
        /**
         * Creates a YamlParser for the given type using Cojen Maker if it does not already exist.
         * Keep it in an internal cache.
         */
        fun <T : Any> yamlParser(type: KClass<T>, nrOfInitArgs: Int = type.constructors.first().parameters.size): AbstractYamlParser<T> {
            return yamlParsers.getOrPut(parserName(type, nrOfInitArgs)) {
                YamlParserCojen(type, nrOfInitArgs)
                    .buildYamlParser()
                    .finish()
                    .getConstructor(KClass::class.java, Integer::class.java)
                    .newInstance(type, nrOfInitArgs) as YamlParserCojen<*>
            } as YamlParserCojen<T>
        }
    }
    /**
     * Used to get a parser for other Type using the same parsing approach.
     */
    override fun <T : Any> yamlParser(type: KClass<T>) = YamlParserCojen.yamlParser(type)

    fun<T : Any> yamlParser(type: Class<T>) = YamlParserCojen.yamlParser(type.kotlin)

    /**
     * Do not change this method in YamlParserCojen.
     */
    override fun newInstance(args: Map<String, Any>): T {
        throw UnsupportedOperationException("This method is overridden in a subclass dynamically generated by buildYamlParser() function!")
    }

    @OptIn(ExperimentalStdlibApi::class)
    private fun buildYamlParser() : ClassMaker {
        // isto vai ter que ser alterado para ir buscar os parametros do construtor que sejam realmente necessarios
        val parameters = type.java.constructors.first { it.parameters.size == nrOfInitArgs }.parameters
        val className = parserName(type, nrOfInitArgs)

        // Criar a classe com o nome certo e extender a classe YamlParserCojen
        val classMaker = ClassMaker.begin(className).public_().extend(YamlParserCojen::class.java).public_()

        // Adicionar os campos necessarios
        classMaker.addField(KClass::class.java, "type").private_().final_()
        classMaker.addField(Integer::class.java, "nrOfInitArgs").private_().final_()

        // Adicionar o construtor
        val constructor = classMaker.addConstructor(KClass::class.java, Integer::class.java).public_()

        // Adicionar os campos
        constructor.field("type").set(constructor.param(0))
        constructor.field("nrOfInitArgs").set(constructor.param(1))

        // Adicionar o super()
        constructor.invokeSuperConstructor(constructor.param(0), constructor.param(1))

        // Adicionar o metodo newInstance
        val newInstanceMethod = classMaker.addMethod(Any::class.java, "newInstance", Map::class.java).public_().override()
        val args = newInstanceMethod.param(0)

        val constructorArgs = mutableListOf<Variable>()
        if(nrOfInitArgs == 0){
            val primitiveValue = args.invoke("get", "#")
            val newValue = if(type.java.isPrimitive) {
                newInstanceMethod.`var`(type.java)
                    .invoke("valueOf", primitiveValue.cast(String::class.java))
            }
            else { // caso de String
                primitiveValue.cast(String::class.java)
            }
            newInstanceMethod.return_(newValue)
            return classMaker
        }
        parameters.forEach { param ->
            val paramName = param.name
            val value = args.invoke("get", paramName)
            val newValue = when (param.type) {
                Int::class.java -> newInstanceMethod.`var`(Int::class.java)
                    .invoke("valueOf", value.cast(String::class.java))

                Long::class.java -> newInstanceMethod.`var`(Long::class.java)
                    .invoke("valueOf", value.cast(String::class.java))

                Double::class.java -> newInstanceMethod.`var`(Double::class.java)
                    .invoke("valueOf", value.cast(String::class.java))

                Float::class.java -> newInstanceMethod.`var`(Float::class.java)
                    .invoke("valueOf", value.cast(String::class.java))

                Short::class.java -> newInstanceMethod.`var`(Short::class.java)
                    .invoke("valueOf", value.cast(String::class.java))

                Byte::class.java -> newInstanceMethod.`var`(Byte::class.java)
                    .invoke("valueOf", value.cast(String::class.java))

                String::class.java -> value.cast(String::class.java)

                List::class.java -> {
                    TODO()
                }

                // O else deveria ser quando ele chega no caso do Address ou outros objectos
                else -> {
                    val classifier = param.type
                    newInstanceMethod.invoke("yamlParser", classifier).invoke("newInstance", value.cast(Map::class.java)).cast(classifier)
                }
            }
            constructorArgs.add(newValue)
        }

        val constructorCall = newInstanceMethod.new_(type.java, *constructorArgs.toTypedArray())
        newInstanceMethod.return_(constructorCall)
        return classMaker
    }

}

